# Use the node Alpine image
FROM node:22-alpine

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first to cache layers
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app listens on
EXPOSE 3000

# Start command
CMD ["npm", "start"]
